{{cookiecutter.product_name}}:
  outputs:
    dev:
      account: "SRLSHZB-RC25629"
      database: "{{cookiecutter.domain_name}}_db"
      # {% raw %}
      # user: "{{ env_var('SNF_USER') }}"
      # password:  "{{ env_var('SNF_PASSWORD') }}"
      user: gb
      password: Gau@snowland#1
      role:  "{{cookiecutter.domain_name}}_engginer"
      schema: "{{cookiecutter.product_name}}"
      threads: 1
      type: snowflake
      warehouse:  "{{cookiecutter.domain_name}}_wh"
  target: dev
