{{cookiecutter.product_name}}:
  outputs:
    dev:
      account: "KUTQCBB-VF37130"
      database: "{{cookiecutter.domain_name}}_db"
      user: "gb"
      password: "Gau@snowland#1"
      role:  "{{cookiecutter.domain_name}}_engginer"
      schema: "{{cookiecutter.product_name}}"
      threads: 1
      type: snowflake
      warehouse:  "{{cookiecutter.domain_name}}_wh"
  target: dev
