{{cookiecutter.contract}}:
  outputs:
    dev:
      account: "ik00045.ap-southeast-1"
      database: "{{cookiecutter.database}}"
      {% raw %}
      user: "{{ env_var('SNF_USER') }}"
      password:  "{{ env_var('SNF_PASSWORD') }}"
      {% endraw %}
      role:  "{{cookiecutter.role}}"
      schema: "{{cookiecutter.schema}}"
      threads: 1
      type: snowflake
      warehouse:  "{{cookiecutter.wh_name}}"
  target: dev
