{{cookiecutter.project}}:
{% raw %}
  outputs:
    dev:
      account: "{{ env_var('SNF_ACCOUNT') }}"
      database: "{{ env_var('SNF_DB_NAME') }}"
      password:  "{{ env_var('SNF_PASSWORD') }}"
      role:  "{{ env_var('SNF_ROLE') }}"
      schema: "prod"
      threads: 1
      type: snowflake
      user: "{{ env_var('SNF_USER') }}"
      warehouse:  "{{ env_var('SNF_WH_NAME') }}"
  target: dev
{% endraw %}